#!/bin/bash

export UWKGM_BASE_DIR="$(realpath $(dirname $BASH_SOURCE))"

source $UWKGM_BASE_DIR/bin/conf
source $UWKGM_BASE_DIR/conf/uwkgm
source $UWKGM_BASE_DIR/conf/servers
source $UWKGM_BASE_DIR/conf/databases
source $UWKGM_BASE_DIR/conf/packages

if [[ $1 == api ]]; then
    $UWKGM_BASE_DIR/bin/api $@

elif [[ $1 == ui ]]; then
    $UWKGM_BASE_DIR/bin/ui $@

fi
